#
#  GemUO
#
#  (c) 2005-2010 Max Kellermann <max@duempel.org>
#  (c) 2010 Kai Sassmannshausen <kai@sassie.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; version 2 of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#

FLAG_FEMALE = 0x02
FLAG_POISON = 0x04
FLAG_YELLOW = 0x08
FLAG_MOVABLE = 0x20
FLAG_WAR_MODE = 0x40
FLAG_HIDDEN = 0x80

NORTH = 0x0
NORTH_EAST = 0x1
EAST = 0x2
SOUTH_EAST = 0x3
SOUTH = 0x4
SOUTH_WEST = 0x5
WEST = 0x6
NORTH_WEST = 0x7
RUNNING = 0x80

SERIAL_PLAYER = 0x80000000

ITEM_BANDAGE = 0xe21

ITEM_DRUMS = 0xe9c
ITEM_TAMOURINE = 0xe9d
ITEM_TAMOURINE_TASSEL = 0xe9e
ITEM_LEAP_HARP = 0xeb2
ITEM_HARP = 0xeb1
ITEM_LUTE = 0xeb3
ITEM_BAMBOO_FLUTE = 0x2805

ITEM_CROOK = 0xe81

ITEM_DAGGER = 0xf52
ITEM_BUTCHER_KNIFE1 = 0x13F6
ITEM_BUTCHER_KNIFE2 = 0x13F7

ITEM_WAND1 = 0xDF2
ITEM_WAND2 = 0xDF3
ITEM_WAND3 = 0xDF4
ITEM_WAND4 = 0xDF5

ITEM_RECALL_SCROLL = 0x1f4c
ITEM_MARK_SCROLL = 0x1f59

ITEM_FISH_STEAK = 0x97B

ITEMS_INSTRUMENTS = (
    ITEM_DRUMS,
    ITEM_TAMOURINE,
    ITEM_TAMOURINE_TASSEL,
    ITEM_LEAP_HARP,
    ITEM_HARP,
    ITEM_LUTE,
    ITEM_BAMBOO_FLUTE,
    )
ITEMS_INSTRUMENTS = set(ITEMS_INSTRUMENTS)

ITEMS_SCOLLS = (
    ITEM_RECALL_SCROLL,
    ITEM_MARK_SCROLL,
    )

ITEMS_WEAPONS_FENCING = (
    ITEM_DAGGER,
    )

ITEMS_WEAPONS_SWORD = (
    ITEM_BUTCHER_KNIFE1,
    ITEM_BUTCHER_KNIFE2
    )

ITEMS_WEAPONS_MACE = (
    ITEM_CROOK,
    ITEM_WAND1,
    ITEM_WAND2,
    ITEM_WAND3,
    ITEM_WAND4,
    )

ITEMS_WEAPONS = \
    ITEMS_WEAPONS_FENCING + \
    ITEMS_WEAPONS_SWORD + \
    ITEMS_WEAPONS_MACE

ITEMS_FOOD = (
    ITEM_FISH_STEAK,
    )

CREATURE_EAGLE = 0x5
CREATURE_BIRD = 0x6
CREATURE_DIRE_WOLF = 0x17
CREATURE_GREY_WOLF1 = 0x19
CREATURE_GREY_WOLF2 = 0x1a
CREATURE_GREY_WOLF3 = 0x1b
CREATURE_WHITE_WOLF1 = 0x22
CREATURE_WHITE_WOLF2 = 0x23
CREATURE_WHITE_WOLF3 = 0x24
CREATURE_WHITE_WOLF4 = 0x25
CREATURE_TIMBERWOLF = 0xe1
CREATURE_GORILLA = 0x1d
CREATURE_COW1 = 0xD8
CREATURE_COW2 = 0xE7
CREATURE_BULL1 = 0xE8
CREATURE_BULL2 = 0xE9
CREATURE_HORSE1 = 0xC8
CREATURE_HORSE2 = 0xE2
CREATURE_HORSE3 = 0xE4
CREATURE_HORSE4 = 0xCC
CREATURE_RIDEABLE_LLAMA = 0xDC
CREATURE_DESERT_OSTARD = 0xD2
CREATURE_BLACK_BEAR = 0xD3
CREATURE_POLAR_BEAR = 0xD5
CREATURE_FOREST_OSTARD = 0xDB
CREATURE_FRENZIED_OSTARD = 0xDA
CREATURE_WALRUS = 0xdd
CREATURE_NIGHTMARE = 0x74
CREATURE_LLAMA = 0xDC
CREATURE_GOAT = 0xD1
CREATURE_TIMBER_WOLF = 0xE1
CREATURE_HINT = 0xED
CREATURE_RAT = 0xEE
CREATURE_GREAT_HART = 0xCF
CREATURE_SHEEP = 0xCF
CREATURE_PIG = 0xCB
CREATURE_CAT = 0xC9
CREATURE_DOG = 0xD9
CREATURE_RAT = 0xEE

ANIMALS = (
    CREATURE_EAGLE,
    CREATURE_BIRD,
    CREATURE_DIRE_WOLF,
    CREATURE_GREY_WOLF1,
    CREATURE_GREY_WOLF2,
    CREATURE_GREY_WOLF3,
    CREATURE_WHITE_WOLF1,
    CREATURE_WHITE_WOLF2,
    CREATURE_WHITE_WOLF3,
    CREATURE_WHITE_WOLF4,
    #CREATURE_TIMBERWOLF,
    CREATURE_GORILLA,
    CREATURE_COW1,
    CREATURE_COW2,
    CREATURE_BULL1,
    CREATURE_BULL2,
    CREATURE_HORSE1,
    CREATURE_HORSE2,
    CREATURE_HORSE3,
    CREATURE_HORSE4,
    CREATURE_RIDEABLE_LLAMA,
    CREATURE_DESERT_OSTARD,
    CREATURE_BLACK_BEAR,
    CREATURE_POLAR_BEAR,
    CREATURE_FOREST_OSTARD,
    CREATURE_LLAMA,
    CREATURE_GOAT,
    CREATURE_TIMBER_WOLF,
    CREATURE_HINT,
    CREATURE_RAT,
    CREATURE_GREAT_HART,
    CREATURE_SHEEP,
    CREATURE_PIG,
    CREATURE_CAT,
    CREATURE_DOG,
    CREATURE_RAT,
    )
ANIMALS = set(ANIMALS)

MONSTERS = (
    CREATURE_FRENZIED_OSTARD,
    CREATURE_NIGHTMARE
    )
MONSTERS = set(MONSTERS)

MOUNTS = (
    CREATURE_HORSE1,
    CREATURE_HORSE2,
    CREATURE_HORSE3,
    CREATURE_HORSE4,
    CREATURE_RIDEABLE_LLAMA,
    CREATURE_DESERT_OSTARD,
    CREATURE_FOREST_OSTARD,
    CREATURE_FRENZIED_OSTARD,
    CREATURE_NIGHTMARE,
    )
MOUNTS = set(MOUNTS)
