#
#  GemUO
#
#  (c) 2010 Kai Sassmannshausen <kai@sassie.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; version 2 of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

# 1st circle
SPELL_CLUMSY = 1
SPELL_CREATE_FOOD = 2
SPELL_FEEBLEMIND = 3
SPELL_HEAL = 4
SPELL_MAGIC_ARROW = 5
SPELL_NIGHTSIGHT = 6
SPELL_REACTIVE_ARMOUR = 7
SPELL_WEAKEN = 8

# 2nd circle
SPELL_AGILITY = 9
SPELL_CUNNING = 10
SPELL_CURE = 11
SPELL_HARM = 12
SPELL_MAGIC_TRAP = 13
SPELL_MAGIC_UNTRAP = 14
SPELL_PROTECTION = 15
SPELL_STRENGHT = 16

# 3rd circle
SPELL_BLESS = 17
SPELL_FIREBALL = 18
SPELL_MAGIC_LOCK = 19
SPELL_POISON = 20
SPELL_TELEKINESIS = 21
SPELL_TELEPORT = 22
SPELL_UNLOCK = 23
SPELL_WALL_OF_STONE = 24

# 4th circle
SPELL_ARCH_CURE = 25
SPELL_ARCH_PROTECTION = 26
SPELL_CURSE = 27
SPELL_FIRE_FIELD = 28
SPELL_GREATER_HEAL = 29
SPELL_LIGHTNING = 30
SPELL_MANA_DRAIN = 31
SPELL_RECALL = 32

# 5th circle
SPELL_BLADE_SPIRITS = 33
SPELL_DISPEL_FIELD = 34
SPELL_INCOGNITO = 35
SPELL_MAGIC_REFLECTION = 36
SPELL_MIND_BLAST = 37
SPELL_PARALYZE = 38
SPELL_POISON_FIELD = 39
SPELL_SUMMON_CREATURE = 40

# 6th circle
SPELL_DISPEL = 41
SPELL_ENERGY_BOLT = 42
SPELL_EXPLOSION = 43
SPELL_INVISIBILITY = 44
SPELL_MARK = 45
SPELL_MASS_CURSE = 46
SPELL_PARALYSE_FIELD = 47
SPELL_REVEAL = 48

# 7th circle
SPELL_CHAIN_LIGHTNING = 49
SPELL_ENERGY_FIELD = 50
SPELL_FLAME_STRIKE = 51
SPELL_GATE_TRAVEL = 52
SPELL_MANA_VAMPIRE = 53
SPELL_MASS_DISPEL = 54
SPELL_METEOR_SWARM = 55
SPELL_POLYMORPH = 56

# 8th circle
SPELL_EARTHQUAKE = 57
SPELL_ENERGY_VORTEX = 58
SPELL_RESSURRECTION = 59
SPELL_AIR_ELEMENTAL = 60
SPELL_SUMMON_DEAMON = 61
SPELL_EARTH_ELEMENTAL = 62
SPELL_FIRE_ELEMENTAL = 63
SPELL_WATER_ELEMENTAL = 64
